baseurl = "http://datanerds.io/"
languageCode = "en-us"
title = "datanerds.io"

[Params]
  logo = "img/logo.png"
  github = "https://github.com/datanerds-io"
  showsRSS = true
  copyright = "Copyright Â© 2017 datanerds.io. <a href=\"http://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>."
  analytics = "UA-75585044-1"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  authors = "authors"
